name: scaffold_gs
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.8
  - plyfile=1.1
  - python=3.10
  - pip=22.3.1
  - pytorch=2.4.0
  - torchaudio=2.4.0
  - torchvision=0.20.1
  - pytorch-scatter
  - tqdm
  - pip:
    - einops
    - wandb
    - lpips
    - laspy
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn